### ISSUE TITLE
"Code" visually present on widget

### ISSUE THREAD

**Issue by rinogo** [jorgemorgado/dashing-doughnutchart#1]
First off, thanks for this great widget!  I hope it will work well for what we're trying to do! (Display NPS scores).  I just finished a basic installation following the readme instructions.  The widget is showing a bunch of "code".  Any idea what might be going on?

![image](https://cloud.githubusercontent.com/assets/3732514/12906325/5a6e3514-ce9c-11e5-8541-cbceaa2f1d6d.png)

**Comment by rinogo** [comment]
I figured it out - Looks like it's a Dashing bug/"feature".  The directory I used for the dashing-doughnutchart files was `doughnutchart`.  Once I changed it to `doughnut_chart`, it started working as expected:

![image](https://cloud.githubusercontent.com/assets/3732514/12906528/65b9b0f4-ce9e-11e5-917e-63f4751e369b.png)

---

Update: FYI, I used the plugin to create an NPS widget; it works great.  Thanks for making this plugin available! :)
![image](https://cloud.githubusercontent.com/assets/3732514/12929736/912f86d0-cf31-11e5-80b1-21cc266a9b4b.png)

**Comment by rinogo** [comment]
Reference: https://github.com/Shopify/dashing/issues/307

**Comment by rinogo** [comment]
It might be good to add a little blurb in the documentation regarding how the directory needs to be named.  It might be obvious for Dashing veterans, but for newbies like myself, it's an easy mistake to make.

**Comment by jorgemorgado** [comment]
Thanks for the notice. I've added the folder creation instructions to the README file.
