### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by Panzam** [jorgemorgado/dashing-doughnutchart#2]
Hello Jorge,

I would like to add a legend on the charts and change the lines and axis color. Do you know how to do this? 
I´ve tried the chart.js documentation but the colors are not changing.

The widgets are running good on my dashing. 

Thanks & Regards,
Mario

**Comment by Panzam** [comment]
Hello Jorge,
I´m able to change the graphs appearance using options on send_event.
I still don´t know how to add legends. Thanks In advance, Mario

**Comment by jorgemorgado** [comment]
Hi Mario,

Not sure I understand your question but you can add a legend to most widgets using the `moreinfo` data bind. Have a look at the [example](https://github.com/jorgemorgado/dashing-doughnutchart/blob/master/doughnut_chart.html) provided. Also, this `data-bind` can be updated via a job (passing JSON) or via API. Check the documentation [page](http://dashing.io/#data). Is this what you are looking for?

Regards,
 Jorge

**Comment by Panzam** [comment]
Hello Jorge,

Thanks for your reply!
 I Would like to add a legend like this one https://camo.githubusercontent.com/64691a56adb5a2536f9ece2d174f645dfb3f8a7f/687474703a2f2f692e696d6775722e636f6d2f4555664f3870762e706e67 

With the values and colors always displaying below the chart. Is it possible? 

Thanks & Regards,
Mario

**Comment by jorgemorgado** [comment]
First the bad news: this is not a widget feature, but rather a Chart.js one. And version 1.0.2 it does not seem to support really what you want. The latest version of [Chart.js](http://www.chartjs.org/docs/#chart-configuration-legend-configuration) does support legend, but the widget does not support the latest version. I might add this support later in the future but as usual, no guarantees.

But there's hope... There is an extension for the old version that adds the legend you are looking for. You can check it [here](https://github.com/bebraw/Chart.js.legend) and there's a demo [here](http://bebraw.github.io/Chart.js.legend/). It should be fairly simple to add this support on the widget but you still need to find a way to pass this data via the API and/or a job. If you make it work, send me a pull request - it could be a good solution until the support for the latest version is implemented.

**Comment by jorgemorgado** [comment]
I've just released the new version with support for Chat.js v2. In the new version, legend is enabled by default so this should do what you were looking.
